title: Yixin Luo's Homepage
page-top-title: Yixin Luo
top-section-bg-text: Computer Science
home-subtitle:Yixin Luo&enfp；|&enfp；罗以欣
copyright-text: '&copy; Yixin Luo 2025 - Present. All Rights Reserved.'
